services:
  docs:
    container_name: docs
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/html:/usr/share/nginx/html:ro"

  master:
    container_name: master
    image: arjones/pyspark:2.4.5
    restart: always
    entrypoint: >
      sh -c "pip3 install pyarrow==0.14.1 && /opt/spark/sbin/start-master.sh"
    environment:
      MASTER: spark://master:7077
      SPARK_NO_DAEMONIZE: 1
      PYTHONPATH: "/opt/spark/python:/opt/spark/python/lib/py4j-0.10.7-src.zip"
    ports:
      - 4040:4040
      - 7077:7077
      - 8080:8080
    volumes:
      - ./code:/app
      - ./dataset:/dataset

  worker1:
    container_name: worker1
    image: arjones/pyspark:2.4.5
    restart: always
    entrypoint: >
      sh -c "pip3 install pyarrow==0.14.1 && /opt/spark/sbin/start-slave.sh spark://master:7077"
    environment:
      MASTER: spark://master:7077
      SPARK_NO_DAEMONIZE: 1
      PYTHONPATH: "/opt/spark/python:/opt/spark/python/lib/py4j-0.10.7-src.zip"
    depends_on:
      - master
    ports:
      - 8081:8080
    volumes:
      - ./code:/app
      - ./dataset:/dataset

  worker2:
    container_name: worker2
    image: arjones/pyspark:2.4.5
    restart: always
    entrypoint: >
      sh -c "pip3 install pyarrow==0.14.1 && /opt/spark/sbin/start-slave.sh spark://master:7077"
    environment:
      MASTER: spark://master:7077
      SPARK_NO_DAEMONIZE: 1
      PYTHONPATH: "/opt/spark/python:/opt/spark/python/lib/py4j-0.10.7-src.zip"
    depends_on:
      - master
    ports:
      - 8082:8080
    volumes:
      - ./code:/app
      - ./dataset:/dataset

  jupyter:
    container_name: jupyter
    image: arjones/pyspark:2.4.5
    restart: always
    entrypoint: >
      sh -c "pip3 install pyarrow==0.14.1 && jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --notebook-dir=/notebook"
    environment:
      MASTER: spark://master:7077
      ARROW_PRE_0_15_0_PANDAS_COMPATIBILITY: "1"
      PYTHONPATH: "/opt/spark/python:/opt/spark/python/lib/py4j-0.10.7-src.zip"
      PYSPARK_PYTHON: python3
    depends_on:
      - master
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebook:/notebook
      - ./dataset:/dataset
      - ./code:/app